package primero;
// Generated 22-dic-2016 14:53:05 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private int idNumerico;
	private String descripcion;
	private Integer stockActual;
	private Integer stockMinimo;
	private Integer pvp;
	private Set<Ventas> ventases = new HashSet<Ventas>(0);

	public Productos() {
	}

	public Productos(int idNumerico) {
		this.idNumerico = idNumerico;
	}

	public Productos(int idNumerico, String descripcion, Integer stockActual, Integer stockMinimo, Integer pvp,
			Set<Ventas> ventases) {
		this.idNumerico = idNumerico;
		this.descripcion = descripcion;
		this.stockActual = stockActual;
		this.stockMinimo = stockMinimo;
		this.pvp = pvp;
		this.ventases = ventases;
	}

	public int getIdNumerico() {
		return this.idNumerico;
	}

	public void setIdNumerico(int idNumerico) {
		this.idNumerico = idNumerico;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getStockActual() {
		return this.stockActual;
	}

	public void setStockActual(Integer stockActual) {
		this.stockActual = stockActual;
	}

	public Integer getStockMinimo() {
		return this.stockMinimo;
	}

	public void setStockMinimo(Integer stockMinimo) {
		this.stockMinimo = stockMinimo;
	}

	public Integer getPvp() {
		return this.pvp;
	}

	public void setPvp(Integer pvp) {
		this.pvp = pvp;
	}

	public Set<Ventas> getVentases() {
		return this.ventases;
	}

	public void setVentases(Set<Ventas> ventases) {
		this.ventases = ventases;
	}

}
