package primero;
// Generated 22-dic-2016 13:41:10 by Hibernate Tools 5.2.0.Beta1

/**
 * Estadisticas generated by hbm2java
 */
public class Estadisticas implements java.io.Serializable {

	private String temporada;
	private Jugadores jugadores;
	private float puntosPorPartido;
	private float asistenciasPorPartido;
	private float taponesPorPartido;
	private float rebotesPorPartido;

	public Estadisticas() {
	}

	public Estadisticas(String temporada, Jugadores jugadores, float puntosPorPartido, float asistenciasPorPartido,
			float taponesPorPartido, float rebotesPorPartido) {
		this.temporada = temporada;
		this.jugadores = jugadores;
		this.puntosPorPartido = puntosPorPartido;
		this.asistenciasPorPartido = asistenciasPorPartido;
		this.taponesPorPartido = taponesPorPartido;
		this.rebotesPorPartido = rebotesPorPartido;
	}

	public String getTemporada() {
		return this.temporada;
	}

	public void setTemporada(String temporada) {
		this.temporada = temporada;
	}

	public Jugadores getJugadores() {
		return this.jugadores;
	}

	public void setJugadores(Jugadores jugadores) {
		this.jugadores = jugadores;
	}

	public float getPuntosPorPartido() {
		return this.puntosPorPartido;
	}

	public void setPuntosPorPartido(float puntosPorPartido) {
		this.puntosPorPartido = puntosPorPartido;
	}

	public float getAsistenciasPorPartido() {
		return this.asistenciasPorPartido;
	}

	public void setAsistenciasPorPartido(float asistenciasPorPartido) {
		this.asistenciasPorPartido = asistenciasPorPartido;
	}

	public float getTaponesPorPartido() {
		return this.taponesPorPartido;
	}

	public void setTaponesPorPartido(float taponesPorPartido) {
		this.taponesPorPartido = taponesPorPartido;
	}

	public float getRebotesPorPartido() {
		return this.rebotesPorPartido;
	}

	public void setRebotesPorPartido(float rebotesPorPartido) {
		this.rebotesPorPartido = rebotesPorPartido;
	}

}
