/*
 * Aeropuerto.java
 *
 * Generated with Matisse Schema Definition Language 9.1.9
 * Generation date: Wed Jan 18 09:38:54 2017
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package aereo;

import com.matisse.reflect.*;

/**
 * <code>Aeropuerto</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Aeropuerto extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.9
     * Generation Date: Wed Jan 18 09:38:54 2017
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Aeropuerto</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("aereo.Aeropuerto"));

    /**
     * Gets the <code>Aeropuerto</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Aeropuerto(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Aeropuerto(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Aeropuerto.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Aeropuerto.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Aeropuerto.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Aeropuerto.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'nombre' */

    /** Attribute <code>nombre</code> cache ID */
    private static int nombreCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombre",CID));

    /**
     * Gets the <code>nombre</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombreAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nombreCID);
    }


    /**
     * Gets the <code>nombre</code> attribute value.
     * @return the value
     *
     * @see #setNombre
     * @see #removeNombre
     */
    public final String getNombre() {
        return getString(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombre</code> attribute value.
     * @param val the new value
     *
     * @see #getNombre
     * @see #removeNombre
     */
    public final void setNombre(String val) {
        setString(getNombreAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombre</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final void removeNombre() {
        removeValue(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final boolean isNombreNull() {
        return isNull(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final boolean isNombreDefaultValue() {
        return isDefaultValue(getNombreAttribute(getMtDatabase()));
    }


    /* Attribute 'pais' */

    /** Attribute <code>pais</code> cache ID */
    private static int paisCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("pais",CID));

    /**
     * Gets the <code>pais</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getPaisAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(paisCID);
    }


    /**
     * Gets the <code>pais</code> attribute value.
     * @return the value
     *
     * @see #setPais
     * @see #removePais
     */
    public final String getPais() {
        return getString(getPaisAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>pais</code> attribute value.
     * @param val the new value
     *
     * @see #getPais
     * @see #removePais
     */
    public final void setPais(String val) {
        setString(getPaisAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>pais</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getPais
     * @see #setPais
     */
    public final void removePais() {
        removeValue(getPaisAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getPais
     * @see #setPais
     */
    public final boolean isPaisNull() {
        return isNull(getPaisAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getPais
     * @see #setPais
     */
    public final boolean isPaisDefaultValue() {
        return isDefaultValue(getPaisAttribute(getMtDatabase()));
    }


    /* Attribute 'numeropistas' */

    /** Attribute <code>numeropistas</code> cache ID */
    private static int numeropistasCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("numeropistas",CID));

    /**
     * Gets the <code>numeropistas</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNumeropistasAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(numeropistasCID);
    }


    /**
     * Gets the <code>numeropistas</code> attribute value.
     * @return the value
     *
     * @see #setNumeropistas
     * @see #removeNumeropistas
     */
    public final int getNumeropistas() {
        return getInteger(getNumeropistasAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>numeropistas</code> attribute value.
     * @param val the new value
     *
     * @see #getNumeropistas
     * @see #removeNumeropistas
     */
    public final void setNumeropistas(int val) {
        setInteger(getNumeropistasAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>numeropistas</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNumeropistas
     * @see #setNumeropistas
     */
    public final void removeNumeropistas() {
        removeValue(getNumeropistasAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getNumeropistas
     * @see #setNumeropistas
     */
    public final boolean isNumeropistasNull() {
        return isNull(getNumeropistasAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNumeropistas
     * @see #setNumeropistas
     */
    public final boolean isNumeropistasDefaultValue() {
        return isDefaultValue(getNumeropistasAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'operado_por' */

    /** Relationship <code>operado_por</code> cache ID */
    private static int operado_porCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("operado_por",CID));

    /**
     * Gets the <code>operado_por</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getOperado_porRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(operado_porCID);
    }

    /**
     * Gets the <code>operado_por</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getOperado_porSize
     * @see #operado_porIterator
     * @see #setOperado_por
     * @see #removeOperado_por
     */
    public final aereo.Compania[] getOperado_por() {
        return (aereo.Compania[])getSuccessors(getOperado_porRelationship(getMtDatabase()), aereo.Compania.class);
    }

    /**
     * Counts the <code>operado_por</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getOperado_por
     * @see #operado_porIterator
     * @see #setOperado_por
     * @see #removeOperado_por
     */
    public final int getOperado_porSize() {
        return getSuccessorSize(getOperado_porRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>operado_por</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getOperado_por
     * @see #getOperado_porSize
     * @see #setOperado_por
     * @see #removeOperado_por
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> operado_porIterator() {
        return this.<E>successorIterator(getOperado_porRelationship(getMtDatabase()), aereo.Compania.class);
    }

    /**
     * Sets the <code>operado_por</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getOperado_por
     * @see #getOperado_porSize
     * @see #operado_porIterator
     * @see #removeOperado_por
     */
    public final void setOperado_por(aereo.Compania[] succs) {
        setSuccessors(getOperado_porRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>operado_por</code> successors list.
     * @param succ the object to add
     *
     * @see #getOperado_por
     * @see #getOperado_porSize
     * @see #operado_porIterator
     * @see #setOperado_por
     * @see #removeOperado_por
     */
    public final void prependOperado_por(aereo.Compania succ) {
        prependSuccessor(getOperado_porRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>operado_por</code> successors list.
     * @param succ the object to add
     *
     * @see #getOperado_por
     * @see #setOperado_por
     * @see #removeOperado_por
     * @see #getOperado_porSize
     * @see #operado_porIterator
     */
    public final void appendOperado_por(aereo.Compania succ) {
        appendSuccessor(getOperado_porRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>operado_por</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getOperado_por
     * @see #setOperado_por
     * @see #removeOperado_por
     * @see #getOperado_porSize
     * @see #operado_porIterator
     */
    public final void appendOperado_por(aereo.Compania[] succs) {
        addSuccessors(getOperado_porRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>operado_por</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getOperado_por
     * @see #setOperado_por
     * @see #getOperado_porSize
     * @see #operado_porIterator
     */
    public void removeOperado_por(aereo.Compania[] succs) {
        removeSuccessors(getOperado_porRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>operado_por</code> successors list.
     * @param succ the object to remove
     *
     * @see #getOperado_por
     * @see #setOperado_por
     * @see #getOperado_porSize
     * @see #operado_porIterator
     */
    public void removeOperado_por(aereo.Compania succ) {
        removeSuccessor(getOperado_porRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>operado_por</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearOperado_por() {
        clearSuccessors(getOperado_porRelationship(getMtDatabase()));
    }


    /* Relationship 'posee' */

    /** Relationship <code>posee</code> cache ID */
    private static int poseeCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("posee",CID));

    /**
     * Gets the <code>posee</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getPoseeRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(poseeCID);
    }

    /**
     * Gets the <code>posee</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getPoseeSize
     * @see #poseeIterator
     * @see #setPosee
     * @see #removePosee
     */
    public final aereo.Vehiculo[] getPosee() {
        return (aereo.Vehiculo[])getSuccessors(getPoseeRelationship(getMtDatabase()), aereo.Vehiculo.class);
    }

    /**
     * Counts the <code>posee</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getPosee
     * @see #poseeIterator
     * @see #setPosee
     * @see #removePosee
     */
    public final int getPoseeSize() {
        return getSuccessorSize(getPoseeRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>posee</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getPosee
     * @see #getPoseeSize
     * @see #setPosee
     * @see #removePosee
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> poseeIterator() {
        return this.<E>successorIterator(getPoseeRelationship(getMtDatabase()), aereo.Vehiculo.class);
    }

    /**
     * Sets the <code>posee</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getPosee
     * @see #getPoseeSize
     * @see #poseeIterator
     * @see #removePosee
     */
    public final void setPosee(aereo.Vehiculo[] succs) {
        setSuccessors(getPoseeRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>posee</code> successors list.
     * @param succ the object to add
     *
     * @see #getPosee
     * @see #getPoseeSize
     * @see #poseeIterator
     * @see #setPosee
     * @see #removePosee
     */
    public final void prependPosee(aereo.Vehiculo succ) {
        prependSuccessor(getPoseeRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>posee</code> successors list.
     * @param succ the object to add
     *
     * @see #getPosee
     * @see #setPosee
     * @see #removePosee
     * @see #getPoseeSize
     * @see #poseeIterator
     */
    public final void appendPosee(aereo.Vehiculo succ) {
        appendSuccessor(getPoseeRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>posee</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getPosee
     * @see #setPosee
     * @see #removePosee
     * @see #getPoseeSize
     * @see #poseeIterator
     */
    public final void appendPosee(aereo.Vehiculo[] succs) {
        addSuccessors(getPoseeRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>posee</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getPosee
     * @see #setPosee
     * @see #getPoseeSize
     * @see #poseeIterator
     */
    public void removePosee(aereo.Vehiculo[] succs) {
        removeSuccessors(getPoseeRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>posee</code> successors list.
     * @param succ the object to remove
     *
     * @see #getPosee
     * @see #setPosee
     * @see #getPoseeSize
     * @see #poseeIterator
     */
    public void removePosee(aereo.Vehiculo succ) {
        removeSuccessor(getPoseeRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>posee</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearPosee() {
        clearSuccessors(getPoseeRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Aeropuerto(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Aeropuerto]";
    }
}
