/*
 * Avion.java
 *
 * Generated with Matisse Schema Definition Language 9.1.9
 * Generation date: Wed Jan 18 09:38:54 2017
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package aereo;

import com.matisse.reflect.*;

/**
 * <code>Avion</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Avion extends aereo.Vehiculo {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.9
     * Generation Date: Wed Jan 18 09:38:54 2017
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Avion</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("aereo.Avion"));

    /**
     * Gets the <code>Avion</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Avion(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Avion(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Avion.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Avion.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Avion.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Avion.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'nmotores' */

    /** Attribute <code>nmotores</code> cache ID */
    private static int nmotoresCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nmotores",CID));

    /**
     * Gets the <code>nmotores</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNmotoresAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nmotoresCID);
    }


    /**
     * Gets the <code>nmotores</code> attribute value.
     * @return the value
     *
     * @see #setNmotores
     * @see #removeNmotores
     */
    public final int getNmotores() {
        return getInteger(getNmotoresAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nmotores</code> attribute value.
     * @param val the new value
     *
     * @see #getNmotores
     * @see #removeNmotores
     */
    public final void setNmotores(int val) {
        setInteger(getNmotoresAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nmotores</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNmotores
     * @see #setNmotores
     */
    public final void removeNmotores() {
        removeValue(getNmotoresAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getNmotores
     * @see #setNmotores
     */
    public final boolean isNmotoresNull() {
        return isNull(getNmotoresAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNmotores
     * @see #setNmotores
     */
    public final boolean isNmotoresDefaultValue() {
        return isDefaultValue(getNmotoresAttribute(getMtDatabase()));
    }


    /* Attribute 'potencia' */

    /** Attribute <code>potencia</code> cache ID */
    private static int potenciaCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("potencia",CID));

    /**
     * Gets the <code>potencia</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getPotenciaAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(potenciaCID);
    }


    /**
     * Gets the <code>potencia</code> attribute value.
     * @return the value
     *
     * @see #setPotencia
     * @see #removePotencia
     */
    public final int getPotencia() {
        return getInteger(getPotenciaAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>potencia</code> attribute value.
     * @param val the new value
     *
     * @see #getPotencia
     * @see #removePotencia
     */
    public final void setPotencia(int val) {
        setInteger(getPotenciaAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>potencia</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getPotencia
     * @see #setPotencia
     */
    public final void removePotencia() {
        removeValue(getPotenciaAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getPotencia
     * @see #setPotencia
     */
    public final boolean isPotenciaNull() {
        return isNull(getPotenciaAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getPotencia
     * @see #setPotencia
     */
    public final boolean isPotenciaDefaultValue() {
        return isDefaultValue(getPotenciaAttribute(getMtDatabase()));
    }


    /* Attribute 'modelo' */

    /** Attribute <code>modelo</code> cache ID */
    private static int modeloCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("modelo",CID));

    /**
     * Gets the <code>modelo</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getModeloAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(modeloCID);
    }


    /**
     * Gets the <code>modelo</code> attribute value.
     * @return the value
     *
     * @see #setModelo
     * @see #removeModelo
     */
    public final String getModelo() {
        return getString(getModeloAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>modelo</code> attribute value.
     * @param val the new value
     *
     * @see #getModelo
     * @see #removeModelo
     */
    public final void setModelo(String val) {
        setString(getModeloAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>modelo</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getModelo
     * @see #setModelo
     */
    public final void removeModelo() {
        removeValue(getModeloAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getModelo
     * @see #setModelo
     */
    public final boolean isModeloNull() {
        return isNull(getModeloAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getModelo
     * @see #setModelo
     */
    public final boolean isModeloDefaultValue() {
        return isDefaultValue(getModeloAttribute(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Avion(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Avion]";
    }
}
